### ISSUE TITLE
EU041 – Refatorar Tipos Documentais

### ISSUE THREAD

**Issue by RobertoMarconi** [prodest/sistema-classificacao-documental#7]
7.41.1.	Narrativa
Como um usuário do sistema devo manter o cadastro de tipos documentais para fornecer uma base unificada de tipos documentais, de forma a permitir a manutenção de Tabelas de Temporalidade e Sigilo Documentais
7.41.2.	Premissas
Toda mudança deverá ser registrada em auditoria.
Esta estória de usuário é de acesso restrito e necessita de autenticação.

**Comment by viniciusgazzoli** [comment]
Criar as atividades e  a estimativa de tempo:

- Modelar entidades e relacionamentos
- Desenvolver serviços (Criar, Atualizar, Excluir, Obter por Id, Listar todos) 
- Desenvolver interface
- Executar testes funcionais
