### ISSUE TITLE
EU042 – Tabela de Temporalidade Documental

### ISSUE THREAD

**Issue by RobertoMarconi** [prodest/sistema-classificacao-documental#8]
7.42.1.	Narrativa
Como um usuário do sistema devo manter a Tabela de Temporalidade Documental para permitir determinar prazos de transferência, recolhimento, eliminação e reprodução de documentos
7.42.2.	Premissas
Toda mudança deverá ser registrada em auditoria.
Esta estória de usuário é de acesso restrito e necessita de autenticação.

**Comment by viniciusgazzoli** [comment]
CRIAR AS ISSUES:

Modelar entidades e relacionamentos
Desenvolver serviços (Criar, Atualizar, Excluir, Listar por Plano)
Desenvolver interface
Executar testes funcionais
